version: '3'
services:
    home-assistant:
        image: homeassistant/home-assistant
        container_name: home-assistant
        volumes:
            - ~/docker/home-assistant/config:/config 
        ports: 
            - "8123:8123"
        environment:
            PUID: 1000
            PGID: 1000
            TZ: America/Phoenix
        restart: unless-stopped

    plex:
        image: linuxserver/plex
        container_name: plex
        volumes:
            - ~/docker/plex/config:/config
            - ~/Backup/TV:/data/tvshows
            - ~/Backup/Movies:/data/movies
        network_mode: "host"
        environment:
            PUID: 1000
            PGID: 1000
            TZ: America/Phoenix
            VERSION: public
        restart: unless-stopped

    tautulli:
        depends_on:
            - plex
        image: tautulli/tautulli
        container_name: tautulli
        volumes:
            - ~/docker/tautulli/config:/config
        ports: 
            - "8181:8181"
        environment:
            PUID: 1000
            PGID: 1000
            TZ: America/Phoenix
        restart: unless-stopped

    ombi:
        depends_on:
            - plex
        image: linuxserver/ombi
        container_name: ombi
        volumes:
            - ~/docker/ombi/config:/config
        ports: 
            - "3579:3579"
        environment:
            PUID: 1000
            PGID: 1000
            TZ: America/Phoenix
        restart: unless-stopped
        
    airsonic:
        image: linuxserver/airsonic
        container_name: airsonic
        volumes:
            - ~/docker/airsonic/config:/config
            - ~/Backup/Music:/music
        ports: 
            - "4040:4040"
        environment:
            PUID: 1000
            PGID: 1000
            TZ: America/Phoenix
        restart: unless-stopped

    beets:
        image: linuxserver/beets
        container_name: beets
        volumes:
            - ~/docker/beets/config:/config
            - ~/Music:/music
            - ~/Downloads:/downloads
        ports:
            - "8337:8337"
        environment:
            PUID: 1000
            PGID: 1000
            TZ: America/Phoenix
        restart: unless-stopped

#    letsencrypt:
#        image: linuxserver/letsencrypt
#        container_name: letsencrypt
#        ports:
#            - "443:443"
#        volumes:
#            - ~/docker/letsencrypt/config:/config
#        restart: unless-stopped
#        depends_on:
#            - home-assistant
#            - plex
#            - tautulli
#            - ombi
#            - airsonic
#        environment:
#            PUID: 1000
#            PGID: 1000
#            EMAIL: wiggins.jonathan@gmail.com
#            URL: jonathanwiggins.ddns.net
#            SUBDOMAINS:
#                - homeassistant
#                - plex
#                - tautulli
#                - ombi
#                - airsonic
#            ONLY_SUBDOMAINS: true
#            DHLEVEL: 4096
#            TZ: America/Phoenix
