version: '3.3'
services:
  traefik:
    image: traefik:v2.1.4
    container_name: traefik
    command:
      - --log.level=DEBUG
      - --accesslog=true
      - --entrypoints.web.address=:80
      - --entrypoints.web_secure.address=:443
      - --api
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      # Let's Encrypt
      - --certificatesresolvers.le.acme.dnschallenge=true
      - --certificatesresolvers.le.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.le.acme.email=${EMAIL}
      - --certificatesresolvers.le.acme.storage=traefik/acme.json
      # Testing server to avoid Let's Encrypt rate limiting certs
      #- --certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
    ports:
      - 80:80
      - 443:443
    environment:
      CF_API_EMAIL  : ${EMAIL}
      CF_API_KEY    : ${CF_API_KEY}
    volumes:
      - ${HOME}/web_services/traefik/acme.json:/traefik/acme.json:rw
      - ${HOME}/web_services/.htpasswd:/traefik/.htpasswd:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      # Dashboard
      traefik.enable: 'true'
      traefik.http.routers.traefik.rule: Host(`traefik.${DOMAIN}`)
      traefik.http.routers.traefik.entrypoints: web_secure
      traefik.http.routers.traefik.service: api@internal
      # Auth
      traefik.http.routers.traefik.middlewares: auth
      traefik.http.middlewares.auth.basicauth.usersfile: /traefik/.htpasswd
      # Global https redirect
      traefik.http.routers.https_redirect.rule: hostregexp(`{host:.+}`)
      traefik.http.routers.https_redirect.entrypoints: web
      traefik.http.routers.https_redirect.middlewares: redirect_to_https
      traefik.http.middlewares.redirect_to_https.redirectscheme.scheme: https
      # Let's Encrypt Wildcard certs
      traefik.http.routers.traefik.tls.certresolver: le
      traefik.http.routers.traefik.tls.domains[0].main: ${DOMAIN}
      traefik.http.routers.traefik.tls.domains[0].sans: '*.${DOMAIN}'
    restart: unless-stopped
