---
#          __           __
#     ____/ /___  _____/ /_____  _____
#    / __  / __ \/ ___/ //_/ _ \/ ___/
#   / /_/ / /_/ / /__/ ,< /  __/ /
#   \__,_/\____/\___/_/|_|\___/_/

version: '3'
services:

    home-assistant:
        container_name: home-assistant
        environment:
            PUID: 1000
            PGID: 1000
            TZ: America/Phoenix
        image: homeassistant/home-assistant
        ports: 
            - "8123:8123"
        restart: unless-stopped
        volumes:
            - ~/docker/home-assistant/config:/config 

